from pathlib import Path
p = Path('workflow-templates/github.mjs')
text = p.read_text(encoding='utf-8')
start = text.index("const taskCli=path.join(process.cwd(),'task','task-cli.mjs');")
end = text.index("const sharedFailureFingerprints=new Map();", start)
old = text[start:end]
new = '''const taskCli=path.join(process.cwd(),'task','task-cli.mjs');",
        "const taskRunner=fs.existsSync(taskCli)?'direct':'cli';",
        "const taskMaxBuffer=1024*1024*8;",
        "function parseJson(raw,fallback){try{return JSON.parse(raw||'')}catch{return fallback;}}",
        "function runTask(args){const cmdArgs=taskRunner==='cli'?['cli.mjs','task',...args,'--config-dir','.bosun','--repo-root','.']:[taskCli,...args];return execFileSync('node',cmdArgs,{encoding:'utf8',stdio:['pipe','pipe','pipe'],maxBuffer:taskMaxBuffer}).trim();}",
        "let taskListCache=null;",
        "function loadTaskList(){if(taskListCache)return taskListCache;try{const raw=runTask(['list','--json']);const tasks=parseJson(raw,[]);taskListCache=Array.isArray(tasks)?tasks:[];}catch{taskListCache=[];}return taskListCache;}",
        "function normalizeTaskValue(value){return String(value||'').trim().toLowerCase();}",
        "function normalizeTaskKey(value){return normalizeTaskValue(value).replace(/^#/, '');}",
        "function parseTaskRef(value){const text=String(value||'').trim();if(!text)return null;const match=text.match(/(?:^|[^A-Z0-9_-])([A-Z]+-[A-Z0-9_-]+|[A-F0-9]{8}-[A-F0-9-]{27,})(?=$|[^A-Z0-9_-])/i);return match?String(match[1]||'').trim():null;}",
        "function collectTaskReferenceCandidates(values){const refs=[];for(const value of values){if(value==null)continue;if(Array.isArray(value)){for(const item of value){if(item&&typeof item==='object'){for(const nested of [item.name,item.title,item.value,item.description,item.text,item.body,item.id]){const ref=parseTaskRef(nested);if(ref)refs.push(ref);}}else{const ref=parseTaskRef(item);if(ref)refs.push(ref);}}continue;}if(value&&typeof value==='object'){for(const nested of [value.name,value.title,value.value,value.description,value.text,value.body,value.id]){const ref=parseTaskRef(nested);if(ref)refs.push(ref);}continue;}const ref=parseTaskRef(value);if(ref)refs.push(ref);}return [...new Set(refs.filter(Boolean).map((ref)=>normalizeTaskKey(ref)))];}",
        "function readTaskField(task,path){let current=task;for(const key of path){if(!current||typeof current!=='object')return undefined;current=current[key];}return current;}",
        "function collectTaskCandidates(task){const rawCandidates=[];const push=(value)=>{if(value==null)return;if(Array.isArray(value)){for(const item of value)push(item);return;}rawCandidates.push(value);};push(task?.id);push(task?.taskId);push(task?.number);push(task?.taskNumber);push(task?.meta?.taskId);push(task?.meta?.taskNumber);for(const path of [['meta','taskRefs'],['meta','taskReferences'],['meta','linkedTaskIds'],['meta','linkedTasks'],['meta','sourceTaskIds'],['meta','sourceTasks'],['meta','reviewHealth','taskRefs'],['meta','reviewHealth','taskReferences'],['meta','prContext','taskRefs'],['meta','prContext','taskReferences'],['meta','prContext','taskId'],['meta','prContext','sourceTaskId'],['meta','prContext','sourceTaskIds'],['meta','prContext','linkedTaskIds'],['meta','prContext','linkedTasks'],['meta','prContext','issueNumber'],['meta','prContext','issueRef'],['meta','prLink','taskId'],['meta','prLink','taskRefs'],['meta','prLink','linkedTaskIds'],['meta','source','taskId'],['meta','source','taskRefs']]){push(readTaskField(task,path));}push(parseTaskRef(task?.title));push(parseTaskRef(task?.description));return collectTaskReferenceCandidates(rawCandidates);}",
        "function buildTaskIndexes(tasks){const byNormalizedId=new Map();const byPrNumber=new Map();const byPrUrl=new Map();const byBranch=new Map();const byTaskRef=new Map();for(const task of tasks){if(!task||typeof task!=='object')continue;const normalizedId=normalizeTaskKey(task?.id);if(normalizedId&&!byNormalizedId.has(normalizedId))byNormalizedId.set(normalizedId,task);const taskPrNumber=Number(task?.prNumber||task?.pr_number||task?.meta?.prNumber||task?.meta?.pr_number||0)||0;if(taskPrNumber>0){const arr=byPrNumber.get(taskPrNumber)||[];arr.push(task);byPrNumber.set(taskPrNumber,arr);}const taskPrUrl=normalizeTaskValue(task?.prUrl||task?.pr_url||task?.meta?.prUrl||task?.meta?.pr_url);if(taskPrUrl){const arr=byPrUrl.get(taskPrUrl)||[];arr.push(task);byPrUrl.set(taskPrUrl,arr);}const taskBranch=normalizeTaskValue(task?.branchName||task?.branch||task?.meta?.branchName||task?.meta?.branch);if(taskBranch){const arr=byBranch.get(taskBranch)||[];arr.push(task);byBranch.set(taskBranch,arr);}for(const ref of collectTaskCandidates(task)){const arr=byTaskRef.get(ref)||[];arr.push(task);byTaskRef.set(ref,arr);}}return {byNormalizedId,byPrNumber,byPrUrl,byBranch,byTaskRef};}",
        "function dedupeTasks(tasks){const seen=new Set();const result=[];for(const task of tasks){if(!task||typeof task!=='object')continue;const key=String(task?.id||task?.taskId||JSON.stringify(task));if(seen.has(key))continue;seen.add(key);result.push(task);}return result;}",
        "function taskStatusRank(task){const status=normalizeTaskValue(task?.status);if(status==='inreview')return 0;if(status==='inprogress')return 1;if(status==='todo')return 2;if(status==='done')return 3;return 4;}",
        "const taskIndexes=buildTaskIndexes(loadTaskList());",
        "function resolveTaskAssociationForPr(item){const matches=[];const reasons=[];const prNumber=Number(item?.n||0)||0;const prUrl=normalizeTaskValue(item?.url);const branch=normalizeTaskValue(item?.branch);if(prNumber>0&&taskIndexes.byPrNumber.has(prNumber)){matches.push(...(taskIndexes.byPrNumber.get(prNumber)||[]));reasons.push('pr-number');}if(prUrl&&taskIndexes.byPrUrl.has(prUrl)){matches.push(...(taskIndexes.byPrUrl.get(prUrl)||[]));reasons.push('pr-url');}if(branch&&taskIndexes.byBranch.has(branch)){matches.push(...(taskIndexes.byBranch.get(branch)||[]));reasons.push('branch');}const metadataRefs=collectTaskReferenceCandidates([item?.title,item?.body,item?.branch,item?.headRefName,item?.headRefOid,item?.url,item?.labels,item?.headRepositoryOwner?.login,item?.author?.login,item?.meta?.taskId,item?.meta?.taskRefs,item?.meta?.taskReferences,item?.meta?.linkedTaskIds,item?.meta?.linkedTasks,item?.meta?.issueRef,item?.meta?.issueNumber]);for(const ref of metadataRefs){if(taskIndexes.byTaskRef.has(ref)){matches.push(...(taskIndexes.byTaskRef.get(ref)||[]));reasons.push('metadata-task-ref');}}const uniqueMatches=dedupeTasks(matches).sort((a,b)=>taskStatusRank(a)-taskStatusRank(b));const normalizedIds=[...new Set(uniqueMatches.map((task)=>normalizeTaskKey(task?.id)).filter(Boolean))];const matchReasons=[...new Set(reasons)];if(uniqueMatches.length===1){const task=uniqueMatches[0];return {taskId:String(task?.id||'').trim()||null,matchType:'resolved',matchReasons};}if(uniqueMatches.length===0){return {taskId:null,matchType:'missing',matchReasons};}const inReviewMatches=uniqueMatches.filter((task)=>normalizeTaskValue(task?.status)==='inreview');const inProgressMatches=uniqueMatches.filter((task)=>normalizeTaskValue(task?.status)==='inprogress');const preferred=inReviewMatches.length===1?inReviewMatches[0]:(inReviewMatches.length===0&&inProgressMatches.length===1?inProgressMatches[0]:null);if(preferred){return {taskId:String(preferred?.id||'').trim()||null,matchType:'preferred-active',matchReasons:[...matchReasons,normalizeTaskValue(preferred?.status)==='inreview'?'status-inreview':'status-inprogress']};}return {taskId:null,matchType:'ambiguous',matchReasons,ambiguousTaskIds:normalizedIds};}",
        "function resolveTaskIdForPr(item){return resolveTaskAssociationForPr(item).taskId;}",
        "function buildReconciliationDecision(item,association){const taskId=String(association?.taskId||'').trim()||null;const snapshot=taskId?(getTaskSnapshot(taskId)||{}):null;const status=normalizeTaskValue(snapshot?.status);const state=normalizeTaskValue(item?.state||item?.status||item?.reviewStatus||'open');const isMerged=item?.merged===true||state==='merged';const isClosed=!isMerged&&(state==='closed'||state==='declined');const hasTask=Boolean(taskId);if(!hasTask){const reason=association?.matchType==='ambiguous'?'ambiguous-task-link':'missing-task-link';return {taskId:null,snapshot:null,nextStatus:null,action:'skip',reasonCode:reason,details:{matchType:association?.matchType||'missing',matchReasons:Array.isArray(association?.matchReasons)?association.matchReasons:[],ambiguousTaskIds:Array.isArray(association?.ambiguousTaskIds)?association.ambiguousTaskIds:[]}};}if(isMerged){if(status==='done'){return {taskId,snapshot,nextStatus:null,action:'skip',reasonCode:'already-done',details:{matchType:association?.matchType||'resolved',matchReasons:Array.isArray(association?.matchReasons)?association.matchReasons:[]}};}return {taskId,snapshot,nextStatus:'done',action:'update',reasonCode:'merged-pr',details:{matchType:association?.matchType||'resolved',matchReasons:Array.isArray(association?.matchReasons)?association.matchReasons:[]}};}if(isClosed){return {taskId,snapshot,nextStatus:null,action:'skip',reasonCode:'closed-pr',details:{matchType:association?.matchType||'resolved',matchReasons:Array.isArray(association?.matchReasons)?association.matchReasons:[]}};}if(status==='done'){return {taskId,snapshot,nextStatus:null,action:'skip',reasonCode:'task-already-done',details:{matchType:association?.matchType||'resolved',matchReasons:Array.isArray(association?.matchReasons)?association.matchReasons:[]}};}if(status==='inreview'){return {taskId,snapshot,nextStatus:null,action:'skip',reasonCode:'already-inreview',details:{matchType:association?.matchType||'resolved',matchReasons:Array.isArray(association?.matchReasons)?association.matchReasons:[]}};}return {taskId,snapshot,nextStatus:'inreview',action:'update',reasonCode:'open-pr',details:{matchType:association?.matchType||'resolved',matchReasons:Array.isArray(association?.matchReasons)?association.matchReasons:[]}};}",
        "function formatLogRecord(item,decision){return {repo:String(item?.repo||'').trim()||null,prNumber:Number(item?.n||0)||null,prUrl:String(item?.url||'').trim()||null,branch:String(item?.branch||'').trim()||null,taskId:decision?.taskId||null,action:decision?.action||'skip',reasonCode:decision?.reasonCode||'unknown',nextStatus:decision?.nextStatus||null,details:decision?.details||{}};}",
        "function applyTaskReconciliation(item){const association=resolveTaskAssociationForPr(item);const decision=buildReconciliationDecision(item,association);const logRecord=formatLogRecord(item,decision);if(decision.action!=='update'||!decision.taskId||!decision.nextStatus){return {updated:false,taskId:decision.taskId||null,logRecord};}const snapshot=decision.snapshot||{};const existingMeta=snapshot?.meta&&typeof snapshot.meta==='object'?snapshot.meta:{};const existingReviewHealth=existingMeta.reviewHealth&&typeof existingMeta.reviewHealth==='object'?existingMeta.reviewHealth:{};const patch={status:decision.nextStatus,prNumber:Number(item?.n||0)||snapshot?.prNumber||null,prUrl:String(item?.url||snapshot?.prUrl||'').trim()||null,branchName:String(item?.branch||snapshot?.branchName||'').trim()||null,meta:{...existingMeta,reviewHealth:{...existingReviewHealth,status:String(item?.reviewStatus||item?.state||'unknown'),failureScope:String(item?.failureScope||'none'),sharedIncidentId:item?.sharedIncidentId||null,failureFingerprint:item?.failureFingerprint||null,failingWorkflow:item?.failingWorkflow||null,failingJobs:Array.isArray(item?.failedCheckNames)?item.failedCheckNames:[],baseBranch:String(item?.base||snapshot?.baseBranch||'').trim()||null,repo:String(item?.repo||'').trim()||null,updatedAt:new Date().toISOString(),source:'pr-watchdog',reasonCode:decision.reasonCode,matchType:decision.details?.matchType||null,matchReasons:Array.isArray(decision.details?.matchReasons)?decision.details.matchReasons:[]}}};try{runTask(['update',decision.taskId,JSON.stringify(patch)]);return {updated:true,taskId:decision.taskId,logRecord};}catch(error){return {updated:false,taskId:decision.taskId,logRecord:{...logRecord,action:'error',reasonCode:'task-update-failed',details:{...logRecord.details,error:String(error?.message||error)}}};}}",
        "function updateTaskReviewSignal(item){const result=applyTaskReconciliation(item);try{console.log(JSON.stringify({type:'pr-task-reconciliation',...result.logRecord}));}catch{}return result.updated;}",
'''
if old not in text:
    raise SystemExit('old block not found')
p.write_text(text.replace(old, new), encoding='utf-8')
